# Usar la imagen oficial de Nginx
FROM nginx:1.21-alpine

# Eliminar la configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiar nuestra propia configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d

# Copiar los archivos del frontend al directorio que sirve Nginx
COPY ./frontend /usr/share/nginx/html
