services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - scraper-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - scraper-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A backend.main.celery_app worker --loglevel=info -c 4
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - scraper-network

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A backend.main.celery_app worker --loglevel=info -c 4
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - scraper-network

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge
