# Usar una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema para Playwright
RUN apt-get update && apt-get install -y libnss3 libnspr4 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2

# Copiar el archivo de requerimientos e instalar dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Instalar Playwright y su navegador
RUN playwright install chromium --with-deps

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto que usará FastAPI
EXPOSE 8000

# El comando por defecto se definirá en docker-compose.yml
# Esto permite usar la misma imagen para el servidor y el worker
